### ISSUE TITLE
Data Module 생성하기

### ISSUE THREAD

**Issue by Dokyeongyun** [Dokyeongyun/DBMonitoring#274]
**Problem or enhancements and It's Background**
- `Core` Module에는 interface만 존재해야 하며, 이를 구현하는 것은 별도 모듈에서 구현해야 한다.
- `Repository` Module은 잘 분리되어 있으나, `Usecase`는 그렇지 않다.
- `Repository`와 `Usecase` 를 `Data` Module로 통합하자.

**Solutions**
- `Data` Module 생성하기

**TODO Tasks and Cautions**
- [ ] `Data` Module 생성
- [ ] `Usecase` 구현체 `Data` Module로 이동
- [ ] `Repository` Module `Data` Module로 이동
